CREATE TABLE ZERO (
	ID integer PRIMARY KEY AUTOINCREMENT,
	ANIMAL_ID text
);

CREATE TABLE FIRST (
	CASE_ID integer PRIMARY KEY AUTOINCREMENT,
	ANIMAL_ID text PRIMARY KEY AUTOINCREMENT,
	EVENT datetime,
	WEIGHT float,
	EQUIPMENT text,
	DRINK_DURATION text,
	STATUS text,
	TRANSFER datetime
);

CREATE TABLE RAW_DATA (
	RAW_CASE_ID integer PRIMARY KEY AUTOINCREMENT,
	ANIMAL_ID text,
	EVENT datetime,
	WEIGHT float,
	EQUIPMENT text,
	STATUS text,
	TRANSFER datetime
);

CREATE TABLE EQUIPMENT (
	ID integer PRIMARY KEY AUTOINCREMENT,
	TYPE blob,
	MODEL text,
	LOCATION blob,
	PERSON blob,
	CONTACT blob
);

CREATE TABLE METRICS (
	METRICS_ID text,
	EQUIPMENT text,
	CPU_TEMP float,
	INTERNET_STATUS text,
	WIND_SPEED float
);

CREATE TABLE SPRAY (
	SPRAY_ID integer PRIMARY KEY AUTOINCREMENT,
	ANIMAL_ID text,
	EQUIPMENT text,
	TYPE text,
	STATUS text,
	WAIT_TIME datetime,
	DONE_TIME datetime,
	DATA_STATUS text,
	TRANSFER datetime
);







